import type { APIRoute } from 'astro';
import { getGroupedDocs } from './llms-full.txt';

const skippedGroups = ['Getting Started'];

export const GET: APIRoute = async () => {
  const groups = (await getGroupedDocs()).filter(
    ({ label }) => !skippedGroups.includes(label),
  );

  const body = `# Sprites Documentation

> Sprites are persistent, hardware-isolated execution environments for arbitrary code. Unlike traditional serverless functions, Sprites are stateful Linux computers that maintain their filesystem and state between runs.

Sprites is a product by Fly.io that provides instant, secure sandboxes for AI agents and untrusted code execution.

## Key Features

- Persistent ext4 filesystem that survives hibernation
- Automatic hibernation after inactivity (no compute charges when idle)
- Instant wake from hibernation
- Hardware-level isolation via Firecracker microVMs
- HTTP access via unique URLs
- Checkpoint and restore capabilities

## Documentation Sections

- Overview: https://docs.sprites.dev/index.md
- Quickstart: https://docs.sprites.dev/quickstart.md
${groups
  .map(({ label, items }) => {
    const lines = items.map(
      ({ slug, name }) => `  - ${name}: https://docs.sprites.dev/${slug}.md`,
    );
    return `- ${label}:\n${lines.join('\n')}`;
  })
  .join('\n')}

## Use Cases

- AI Code Execution: Execute code generated by language models in isolated, secure environments
- Untrusted Code: Create isolated environments for running user-submitted code safely
- Development Environments: Build persistent dev environments that maintain state
- Long-lived Services: Run services with automatic hibernation and wake-on-request
- CI/CD Tasks: Test code against live git repositories with full environment access
`;

  return new Response(body);
};
